accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns =[
    path('login/',views.user_login,name='user-login'),
    path('register/',views.user_register,name='user_regiter'),
    path('logout/',views.user_logout,name='user_logout'),
]

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns =[
    path('',views.all_articles,name='all_articles'),
    path('article_detail/<id>/', views.article_detail, name='article_detail'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
class publishedArticlemanager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='publish')


class Article(models.Model):
        STATUS = (
            ('draft', 'Draft'),
            ('publish', 'Publish')
        )
        title = models.CharField(max_length=120)
        slug = models.SlugField(max_length=120, unique=True)
        writer = models.ForeignKey(User, on_delete=models.CASCADE)
        body =RichTextUploadingField()
        publish = models.DateTimeField(default=timezone.now)
        updated = models.DateTimeField(auto_now=True)
        status = models.CharField(max_length=20, choices=STATUS, default='draft')
        objects = models.Manager()
        published = publishedArticlemanager()
        objects=models.Manager()

        def get_absolute_url(self):
            return reverse('blog:article_detail', args=[self.id, self.slug])

        def __str__(self):
            return self.title

accounts/views.py
from django.shortcuts import render,redirect
from .form import Userloginform,Userregisterform
from  django.contrib.auth import authenticate,login,logout
from django.contrib import messages
def user_login(request):
    if request.method == 'POST':
        form =Userloginform(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request, user)
                messages.success(request,'your login is successful','success')
                return redirect('blog:all_articles')
            else:
                messages.error(request,'your username or password is wrong','danger')
    else:
        form = Userloginform()
    return render(request,'form.html',{'form':form})
def user_register(request):
     if request.method == 'POST':
          form = Userregisterform(request.POST)
          if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            emailadress = form.cleaned_data['emailadress']
            user = authenticate(request, username=username, password=password,emailadress=emailadress)
            messages.success(request, 'your  register is successful', 'success')
            return redirect('accounts:user-login')
     else:
        form = Userregisterform()
        return render(request,'register.html',{'form':form})

def user_logout(request):
    logout(request)
    messages.success(request,'you logout successfully','success')
    return redirect('blog:all_articles')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Article


def all_articles(request):
    all_articles = Article.objects.filter(status='publish')
    return render(request, 'blog/all_articles.html', {'all_articles': all_articles})


def article_detail(request, id):
    article_detail = Article.objects.get(id=id)
    return render(request, 'blog/article_detail.html', {'article_detail': article_detail})

accounts/templates/form.html
{% extends 'base.html' %}
{% block content %}
    <form action="." method="post" novalidate>
    {% csrf_token %}
      <br>{{ form.as_p }}
    <input type="submit" value="login">
    </form>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% block content %}
   <form action="." method="post" novalidate>
    {% csrf_token %}
      <br>
    <input type="submit" value="login">
    </form>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
     <form action="" method="post">
     {% csrf_token %}
     {{form.as_p }}
         <input type="submit" value="Register" class="btn btn-info">
     </form>
{% endblock %}

blog/templates/blog/all_articles.html
{% extends 'base.html' %}
{%block content %}
    {% for article in all_articles %}
        <hr>
        <a href="{% url 'blog:article_detail' article.id %}" >{{ article.title }}</a><hr>
 {% endfor %}
{%endblock  %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% block content %}

    <br><h1>{{ article_detail.title }}</h1>
        <p>{{ article_detail.body|safe  }}</p>
        <small>{{ article_detail.publish }},</small>
    <small>{{ article_detail.writer }}</small>

{% endblock  %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<style>
body {
  background-color: #dfe3e3;
}
</style>
</head>
<body>

{% include 'inc/navbar.html' %}
{% include 'inc/messages.html' %}
  <div class="p-5 text-center bg-light">
{% block content %}{% endblock %}
</div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
     <P class="alert alert-{{ message.tags }}">{{ message }}</P>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

          <a class="navbar-brand "aria-current="page" href="{% url 'blog:all_articles' %}" >Home</a>
          {% if request.user.is_authenticated %}
           <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_logout' %}" >logout</a>
          {% else %}
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:user-login' %}" >Login</a>
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_regiter' %}" >Register</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>